apiVersion: v1
kind: Service
metadata:
  name: cluster-lb


  labels:
    app: neo4j-cluster

  annotations:
    service.beta.kubernetes.io/azure-load-balancer-mode: default
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
    
spec:
  type: LoadBalancer
  ports:
  - name: bolt
    port: 7687
    protocol: TCP
    targetPort: 7687
  - name: http
    port: 7474
    protocol: TCP
    targetPort: 7474
  selector:
    app: neo4j-cluster
  sessionAffinity: None
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
